### ISSUE TITLE
Should linux install Boost with cmake?

### ISSUE THREAD

**Issue by afucher** [advpl/advpl-language-server-cxx#2]
I run the `script` to build, but I'm getting error with Boost:
```
CMake Error at /opt/cmake-3.10.2-Linux-x86_64/share/cmake-3.10/Modules/FindBoost.cmake:1928 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.

```

What I'm doing wrong?

**Comment by afucher** [comment]
According to this https://askubuntu.com/questions/551876/cmake-3-0-2-cant-find-boost-on-14-04 I need to install `libboost-all-dev`.

Should this be in README?

**Comment by killerall** [comment]
You dont need install it.
just see:
http://www.boost.org/doc/libs/1_66_0/more/getting_started/unix-variants.html

**Comment by vlopes11** [comment]
I wrote a Linux guide to build this project:
https://github.com/advpl/advpl-language-server-cxx/blob/dev/README.md

**Comment by vlopes11** [comment]
Currently only the dev branch is available for Linux build. So:
```bash
$ git clone https://github.com/advpl/advpl-language-server-cxx.git
$ cd advpl-language-server-cxx
$ git pull origin dev
$ git checkout dev
```

Actually I just realized Debian stable (Stretch) is currently using CMake 3.7, which sucks. The guide was wrote with Arch-Linux, and I don't know why the Debian guys are all the time very conservative on this matter, but anyway, here is how to fix it.

1. Install Java (if you don't have)
```bash
# apt-get install default-jdk
```
1. Install Lib Boost and related dependencies to antlr4cpp
```bash
# apt-get install libboost-all-dev pkg-config uuid-dev
```

Set update repository to buster. All of this should be done with root privileges (sudo)
1. Backup your current sources list 
```bash
# cp /etc/apt/sources.list /etc/apt/sources.list.bkp
```
1. Set current distro to buster and update apt cache
```bash
# echo "deb http://ftp.us.debian.org/debian buster main" > /etc/apt/sources.list
# echo "deb-src http://ftp.us.debian.org/debian buster main" >> /etc/apt/sources.list
# apt-get update
# apt-get autoremove
```
1. Remove previous packages
```bash
# apt-get remove build-essential
# apt-get remove cmake
# apt-get autoremove
```
1. Install build-essential and cmake
```bash
# apt-get install build-essential
# apt-get install cmake
```
1. Restore previous source list
```bash
# mv /etc/apt/sources.list.bkp /etc/apt/sources.list
# apt-get update
```

And finally
```bash
$ cmake .
$ make
$ make test
```
I tested this on Debian Stable (Stretch). Which distro are you using?

**Comment by vlopes11** [comment]
Readme updated on [commit 6b1210c](https://github.com/advpl/advpl-language-server-cxx/commit/057d50bdfa5864deef156497fabcf1696feca990)
